### ISSUE TITLE
No documentation on how to configure with a toml file

### ISSUE THREAD

**Issue by adamthedeveloper** [xuri/aurora#10]
I can see the example toma file in the repo. I don't see any examples of how to set the values which leads to trial and error guess work. Please include a detailed writeup on how to configure the toml exactly as the innards would expect them to be.

**Comment by xuri** [comment]
Thanks for your issue, I have added configuration file descriptions in the [wiki](/xuri/aurora/wiki#configuration-file) page.

**Comment by adamthedeveloper** [comment]
Very helpful! Thanks. Really great project also!
