### ISSUE TITLE
Feature Request - Subdirectory

### ISSUE THREAD

**Issue by twocolors** [xuri/aurora#32]
hi, if use nginx and proxy to app , many errors to url '/' , redirect to '/', all must be './'
plz fix this.

**Comment by twocolors** [comment]
@xuri thx, but have some code
`http.Redirect(w, r, "/sample?action=manageSamples", 301)`
`link.WriteString('/tube?server=')`

all redirect use `/`

**Comment by xuri** [comment]
Hi, @twocolors. Thanks for your feedback, I have fixed it.
