### ISSUE TITLE
Update https://github.com/beanstalkd/go-beanstalk to fix indefinite client hang after connection reset

### ISSUE THREAD

**Issue by samuelg** [xuri/aurora#38]
**Description**

We appear to have run into the issue fixed by https://github.com/beanstalkd/go-beanstalk/pull/29. A job that had been created days earlier was never processed until a restart forced the connection to be re-established.

Ideally this module would update the go-beanstalk module to include the above fix.

**Steps to reproduce the issue:**
Unclear how the connection gets in this state to trigger the underlying issue in the go-beanstalk module.

**Describe the results you received:**
Job stuck indefinitely until a restart forced the connection to be re-established

**Describe the results you expected:**
Job should be picked up via ready state

**Output of `go version`:**

```
go version go1.13 linux/amd64
```

**Aurora version or commit ID:**

commit ID: 8024f7a4d7f6

**Environment details (OS, physical, etc.):**

Ubuntu 16.04

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it.

**Comment by samuelg** [comment]
Thank you. Very quick turnaround!
